py = python
SHELL := /bin/bash

build :
	-@echo "No building necessary, run accounts with option -i,-h,-t, or -? from command line, make run is also a valid command"

clean :
	-@echo "XPM and pyc Files cleaned!"
	-@rm -rf *.pyc
	-@rm -rf *.xpm

run :
	-@python CG_hw2

view :
	-@less CG_hw2
